name: PaperKits
main: com.drkrisz.kits.KitsPlugin
version: 0.1.0
api-version: '1.21'
author: Krisz
commands:
  kit:
    description: give a kit or open the kit creator
    usage: "/kit <name>|create|list|edit <name>"
    aliases: [kits]
permissions:
  kits.use:
    description: Allows using /kit and /kits commands
    default: true
  kits.create:
    description: Allows creating kits
    default: true
  kits.admin:
    description: Allows editing and managing all kits
    default: true
